### ISSUE TITLE
setProgress not work in onViewCreated()

### ISSUE THREAD

**Issue by rny** [JDevZone/FillProgressLayout#15] opened 2020-11-14 00:55 UTC
this line not work in onViewCreated() of Fragment
```
        progressbar.setProgress(50, false)
```

Reason:

```
initUI() called setProgress() with an animate before, any following setProgress() not work until animate finished.
```

Fix: the loading should not perform any animate

Line 137 inside initUI()
```
                setProgress(progress, false)
```

**Comment by rny** [comment] 2020-11-14 01:07
```
setProgress(10, true) 
setProgress(50, false)
```

also, the above code should also have problem, the second call will have no effect.

I suggest add **endProgress** variable to remember animate finish position.

**Comment by JDevZone** [comment] 2020-11-27 13:31
First of all Thanks @rny for pointing it out and really digging down to the cause and also suggesting the fix. This will be fixed in next release dropping soon.

**Comment by JDevZone** [comment] 2021-01-26 15:16
Hi @rny ,This issue is fixed now in <a href = "https://github.com/JDevZone/FillProgressLayout/releases/tag/v0.0.7">this</a> release. so, closing this issue now.

**Closed as completed by JDevZone** 2021-01-26 15:16 UTC
